<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  <h1>Login</h1>
  <form action="login.php" method="POST">
    <label>Usuario</label>
    <input name ="user" required/>
    <label>Senha:</label>
    <INput name="senha" id="password"required />

    <button type="submit">Entrar</button>
 </form>
</body>
</html>